### ISSUE TITLE
LineLogger NewLineBuf timestamp format

### ISSUE THREAD

**Issue by mattaezell** [xcat2/goconserver#19]
https://github.com/chenglch/goconserver/blob/4415be43710a8eafaa940300b79d4fe4ed8af92b/console/pipeline/logger.go#L26

Many systems use milliseconds [(elasticsearch)](https://github.com/elastic/elasticsearch/issues/10005), microseconds, or nanoseconds; but 5 zeros is very uncommon.  Consider moving this to 3 or 6.  Better yet, allow the format to be customized in the config file.

**Comment by chenglch** [comment]
@mattaezell , A new build has been uploaded to fix these issues, you could download it from https://github.com/chenglch/goconserver/releases/tag/v0.2.1 .

A new option has been added to help customize the time precision, the default value is microsecond. 
```
console:
  # log the timestamp.
  log_timestamp: true
  # time precison for tcp or udp logger, precison for file logger is always second.
  # Valid options: second, millisecond, microsecond, nanosecond
  time_precision: microsecond
```
